name: Free VPS Bot

on:
  workflow_dispatch:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run Bot
        run: python bot.py
